### ISSUE TITLE
How to run this project  in Win7

### ISSUE THREAD

**Issue by SaddamBInSyed** [AhmetHamzaEmra/Intelegent_Lock#10]
Hi, I am a newbie to python,  So can you please advise me about how to test this project with python? and Is this complete liveness detection project?

Awaiting for your reply.

**Comment by AhmetHamzaEmra** [comment]
Install Ubuntu 😄 

Windows is a pain in the ass when it comes to installing packages with python. 

And for the liveness; it will be wrong if I say it is complete, it is more like a fake image (printouts-photos displayed on different devices) detection. But improvement will come soon (i am working on it)
