### ISSUE TITLE
Issues with data in .csv file? 

### ISSUE THREAD

**Issue by ghost** [AhmetHamzaEmra/Intelegent_Lock#11]
Hello, 

I was taking a look at doing something like this project with a friend, but it looks like the training data in the .csv file (in the liveness detection folder, presumably used by liveness_finetune.py) literally has "..." in it in between the pixel data (so it would look something like "[1, 2, 3] ... [4, 5, 6]" but without any actual data hidden in the "..." part). 
Is there any way you could give access to the picture data (spoofed v.s. not) itself?

Sorry for the trouble, and thanks for your time

**Comment by AhmetHamzaEmra** [comment]
I am sorry but the original dataset contains many of my friends photos and they don't want me to share it. So I cannot share.
