### ISSUE TITLE
where  the directory  of "liveness_detection/img-live/" is ?

### ISSUE THREAD

**Issue by whokhong** [AhmetHamzaEmra/Intelegent_Lock#13]
live_img = ["liveness_detection/img-live/"+f for f in listdir("liveness_detection/img-live/") if isfile(join("liveness_detection/img-live/", f))]

can not find such direcotory     liveness_detection/img-live/

**Comment by AhmetHamzaEmra** [comment]
In my computer 😄 

Because it contains a lot of my friends who don't want me to share the photos, I cannot put it in here
