### ISSUE TITLE
Readme in Details

### ISSUE THREAD

**Issue by shaficse** [AhmetHamzaEmra/Intelegent_Lock#14]
Could you please give us a readme file in details ;e.m. training part , opencv version , test part on this project . Thank you...

**Comment by AhmetHamzaEmra** [comment]
Could you please be more specific? 😄  What exactly you would like to see?

**Comment by shaficse** [comment]
I have solved and successfully run . Is there any paper  of your implementation . If it has , please give me the link .

**Comment by shridhar-pivotchain** [comment]
Hi can you load a sample of data which you used to train the model or the dataset link?

**Comment by AhmetHamzaEmra** [comment]
Sorry, but I cannot share the dataset. It contains my friend's pictures and we had an agreement for me to not share the data. It was the only way to get them participating 😅
