### ISSUE TITLE
Prediction is not stable

### ISSUE THREAD

**Issue by kofaral** [AhmetHamzaEmra/Intelegent_Lock#17]
First of all, thank you for sharing your code.
Second, I have 2 main issues when I use it.
1- The prediction is really good when it works, but suddenly and without changing anything, the liveness score lowers from 99.9% to less than 50% for my real face.
2- The prediction is really poor when I have dark backgrounds.

Do you have explanation or solution for these situations? 
Thanks in advance.

**Comment by MaxwellHan** [comment]
> First of all, thank you for sharing your code.
> Second, I have 2 main issues when I use it.
> 1- The prediction is really good when it works, but suddenly and without changing anything, the liveness score lowers from 99.9% to less than 50% for my real face.
> 2- The prediction is really poor when I have dark backgrounds.
> 
> Do you have explanation or solution for these situations?
> Thanks in advance.

when i test the code, i found that when my face is not in the center of the frame,the prediction will lowers to zero.

**Comment by AhmetHamzaEmra** [comment]
The dataset was small when I was training the network. Please retrain the network again with your own images for a couple of epochs which will solve the issues. Let me know if you have question in there.
