### ISSUE TITLE
  inp = inp.reshape(1,24,100,100,1) ValueError: cannot reshape array of size 720000 into shape (1,24,100,100,1)

### ISSUE THREAD

**Issue by Chandrakala14** [AhmetHamzaEmra/Intelegent_Lock#18]
Hi,

This code working fine with web cam but I am trying to connect IP camera and do the liveliness detection,  but for me getting error as

  **inp = inp.reshape(1,24,100,100,1)
ValueError: cannot reshape array of size 720000 into shape (1,24,100,100,1)**

Can you please help me to solve this

**Comment by AhmetHamzaEmra** [comment]
Hello,  it seems like it doesnt take grayscale images or it still produces 3 color channels. 

could you please check this part if it is working?

**liveimg = cv2.cvtColor(liveimg, cv2.COLOR_BGR2GRAY)**

**Comment by Chandrakala14** [comment]
ok, thanks for the reply.
