### ISSUE TITLE
Liveness detection on multiple detected faces in the frame!

### ISSUE THREAD

**Issue by Anas-Khan93** [AhmetHamzaEmra/Intelegent_Lock#19]
Hi, I am trying to tweak your code to create a liveness detector that can detect the liveness on multiple faces. Since it seems that this liveness detector will use one detected faces liveness result as the truth and if any other face is detected than it will impose the first ones result on everyone of the faces.

Im trying to think of ways but i can't get anywhere, could you please guide me ?

**Comment by AhmetHamzaEmra** [comment]
sorry for the late reply, could you please share the code with me?
