### ISSUE TITLE
Retrain Face liveliness detector

### ISSUE THREAD

**Issue by Zumbalamambo** [AhmetHamzaEmra/Intelegent_Lock#2]
How do we retrain the liveliness detector?

**Comment by AhmetHamzaEmra** [comment]
Hello, 

I added [finetuning script](https://github.com/AhmetHamzaEmra/Intelegent_Lock/blob/master/liveness_finetune.py) in to repository. 
please follow to code, if any problem I would be happy to help you with that

Also, if it is not too much to ask could you please share the dataset with me too. I will not put it online. I am just going to train the network again. 


Happy New Year!

**Comment by Zumbalamambo** [comment]
@AhmetHamzaEmra if you can share with me sample dataset, i can collect more based on the same,...

**Comment by Zumbalamambo** [comment]
also let me know the directory structure that i have to use while collecting data

**Comment by Zumbalamambo** [comment]
Thank you and Happy newyear
