### ISSUE TITLE
Question - Please advise how to create a dataset and train it

### ISSUE THREAD

**Issue by Krammig** [AhmetHamzaEmra/Intelegent_Lock#21]
Hello, 
I a few thousand face images from around the web. 

Can you please explain (or point me to a doc / website) that will describe how I get from face image to the point that is required to run in your app. I assume being the "model". 

I am new to this (retired 65yo IT guy of 44 years in coding) and would love to be able to lean more about this. 

Thanks in advance.

**Comment by kur0saki** [comment]
Hello Krammig,

Basically you need to train the model on your own dataset , the model structure is included in the code , you just need to prepare your dataset and run the model on it.

**Comment by Krammig** [comment]
Thanks for the reply on this.
And by dataset I presume you mean images ?
Cheers

**Comment by AhmetHamzaEmra** [comment]
Hey,

is everything working fine now?
