### ISSUE TITLE
What is the liveness indicator?

### ISSUE THREAD

**Issue by sahilrider** [AhmetHamzaEmra/Intelegent_Lock#24]
You have written that you have used 3D CNN but how will it differentiate between a live image and an image. Could you please elaborate on the distinction criteria or how it works?

**Comment by AhmetHamzaEmra** [comment]
if you use 3D CNN, input becomes video instead of single images. using video is much more applicable since it contains more features than images. Features like eye, hair and lips movements can be captured and it will help our algorithm to classify.

**Comment by sahilrider** [comment]
I can understand it better now. Thanks
