### ISSUE TITLE
detect fake video player on mobile or screen

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [AhmetHamzaEmra/Intelegent_Lock#26]
Hi @AhmetHamzaEmra 
I played my recorded face on camera but liveness can not detect this video was fake.
can you handle that to detect fake video player on mobile or screen?

**Comment by Hatef-Rostamkhani** [comment]
[b3144ca2-4b9c-400f-b50c-7720ab52e190.zip](https://github.com/AhmetHamzaEmra/Intelegent_Lock/files/4873068/b3144ca2-4b9c-400f-b50c-7720ab52e190.zip)

**Comment by pieroashady** [comment]
the detection from live webcam was good enough for me, but why when the input video from file like mp4, the result is unstable? thanks sir
