### ISSUE TITLE
Model hakkında

### ISSUE THREAD

**Issue by mfurkanns** [AhmetHamzaEmra/Intelegent_Lock#28]
Kullanılan pretrained model hakkında bilgilendirir misiniz ? Hangi eğitilmiş model kullanıldı ? Model neleri göz önünde bulundurarak canlılığa karar veriyor ? Modelle ilgili daha fazla bilgiyi nerede bulabilirim ?

**Comment by AhmetHamzaEmra** [comment]
You can find general explanations in the following link -> [Blogpost](https://ahmethamzaemra.github.io/2018/12/28/Intelegence-lock.html)

If you have any specific, question please let me know
