### ISSUE TITLE
Reshape Error 

### ISSUE THREAD

**Issue by Sarim-Zuhair** [AhmetHamzaEmra/Intelegent_Lock#30]
Hi there, I am trying to make a server script based on your project. I only require the liveness detection part and have utilized that code only. My structure of code is such that the client posts a single frame to the server code which should then process and return a boolean corresponding to liveness. However, when I post a frame I get the error on both the client and server sides. Following is the error:

 inp = inp.reshape(1,24,100,100,1)
ValueError: cannot reshape array of size 10000 into shape (1,24,100,100,1)

**Comment by AhmetHamzaEmra** [comment]
the model uses video input. If you want to use a single frame input, please either use v1 (folder in the repo) or stack 24 of those frames and use it that way. Just so you know, second method will not work as expected if you dont finetune with new dataset.

**Comment by Sarim-Zuhair** [comment]
Hi there, could you please guide on how to use v1? I tried running the project but it gives FileNotFoundError because it is not able to find the img-live directory in the indicated directory.

**Comment by Sarim-Zuhair** [comment]
ive_img = ["liveness_detection/img-live/"+f for f in listdir("liveness_detection/img-live/") if isfile(join("liveness_detection/img-live/", f))]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'liveness_detection/img-live/'
