### ISSUE TITLE
do you have any idea about intelegent lock for face recognition android platform ?

### ISSUE THREAD

**Issue by rambabu125** [AhmetHamzaEmra/Intelegent_Lock#5]

**Comment by AhmetHamzaEmra** [comment]
To be honest I don't have any experience with android but I think you should check APIs. For example, [microsoft](https://azure.microsoft.com/en-us/services/cognitive-services/face/) but I am not sure if they support Android enviroment.

**Comment by rambabu125** [comment]
thnx@AhmetHamzaEmra
