### ISSUE TITLE
will this work for photo ?

### ISSUE THREAD

**Issue by clearsensespw** [AhmetHamzaEmra/Intelegent_Lock#8]
hi,
i want to use this as api from my mobile app. will this work for image i send from camera ?

can you mention which algorithm is this ? if any paper link, it will be good

**Comment by AhmetHamzaEmra** [comment]
hello, 
the models are from this [blog post](https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78). it will work from the images from a phone camera but I don't know if there is any implementation of the models.
