### ISSUE TITLE
Illumination change, influence Living  detection

### ISSUE THREAD

**Issue by chenshihao123456** [AhmetHamzaEmra/Intelegent_Lock#9]
i found a problem that The data collected in the morning , then training fintune. in the afternoon , the result is poor.

**Comment by AhmetHamzaEmra** [comment]
Hello,

I am aware of the problem. the reason is that it is starting to overfit the finetuning dataset since you are training with it again and again. I made the change now, it will not save on the last version. if you want to save it you can uncomment that part in the main code.
